import {
  Box,
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Heading,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import { useQuery } from "react-query";
import { Posts } from "../types/posts";

export default function Home() {
  async function fetchPosts() {
    const response = await axios("https://jsonplaceholder.typicode.com/posts");
    return response.data;
  }
  const { isLoading, error, data } = useQuery("postsData", fetchPosts);
  console.log(data);
  return (
    <>
      <Head>
        <title>IMP Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Button>Create Post</Button>
        <Stack>
          <Heading as="h1" size="md" textAlign="center">
            Posts Data
          </Heading>
          <SimpleGrid
            spacing={4}
            templateColumns="repeat(auto-fill, minmax(260px, 1fr))"
          >
            {data?.map((post: Posts) => (
              <Card key={post.id}>
                <CardHeader>
                  <Heading size="md">{post.id}</Heading>
                </CardHeader>
                <CardBody>
                  <Text>{post.title}</Text>
                </CardBody>
                <CardFooter gap={2}>
                  <Button>Edit</Button>
                  <Button>Delete</Button>
                  <Button>Details</Button>
                </CardFooter>
              </Card>
            ))}
          </SimpleGrid>
        </Stack>
      </Box>
    </>
  );
}
